version: '3.1'

services:
  iut-dbm-db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./iut-dbm:/docker-entrypoint-initdb.d
      - ./.temp/iut-dbm:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: dev
      MYSQL_DATABASE: dev
      MYSQL_USER: dev
      MYSQL_PASSWORD: dev

  iut-dbm-memcached:
    image: memcached
    ports:
      - 11211:11211
