version: '3.1'

services:
  iut-dbm-db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    volumes:
      - ./iut-dbm:/docker-entrypoint-initdb.d
      - ./.temp/iut-dbm:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: dev
      MYSQL_DATABASE: dev
      MYSQL_USER: dev
      MYSQL_PASSWORD: dev

  iut-dbm-memcached:
    image: memcached
    ports:
      - 11211:11211

  iut-dbm-mongodb:
    image: mongo
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./.temp/iut-dbm-mongodb:/data
      - ./iut-dbm:/iut-dbm
    ports:
      - 27017:27017

